import{a as b,i as y,S as L}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&d(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();let p=1;const u=40;let E="",w="41728884-677575adccc9f2c5ba20b621f",v=document.querySelector(".gallery");document.querySelector(".form-search").addEventListener("submit",async function(n){n.preventDefault();const o=document.querySelector("span.loader"),i=document.querySelector(".button-loadmore");v.innerHTML="",o.classList.add("visible"),i.classList.remove("visible");const d=document.querySelector(".text-input").value,e={key:w,q:d,image_type:"photo",orientation:"horizontal",safesearch:!0,page:p,per_page:u},r=`https://pixabay.com/api/?${new URLSearchParams(e)}`;try{const t=(await b.get(r)).data;o.classList.remove("visible"),t.hits.length===0?y.error({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}):(t.hits.forEach(a=>{const l=document.createElement("li"),c=document.createElement("img"),g=document.createElement("a"),f=document.createElement("div");c.src=a.webformatURL,c.alt=a.tags,g.href=a.largeImageURL,g.appendChild(c),f.classList.add("image-info"),f.innerHTML=`
                    <p class="likes">Likes <span>${a.likes}</span></p>
                    <p class="views">Views <span>${a.views}</span></p>
                    <p class="comments">Comments <span>${a.comments}</span></p>
                    <p class="downloads">Downloads <span>${a.downloads}</span></p>
                `,l.appendChild(g),l.appendChild(f),v.appendChild(l)}),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),t.hits.length===u&&i.classList.add("visible"))}catch(h){console.error("Error fetching search results:",h),o.classList.remove("visible")}});document.querySelector(".button-loadmore").addEventListener("click",async function(){const n=document.querySelector(".loader-loadmore"),o=document.querySelector(".button-loadmore");n.classList.add("visible"),o.classList.remove("visible");try{p++;const i={key:w,q:E,image_type:"photo",orientation:"horizontal",safesearch:!0,page:p,per_page:u},e=`https://pixabay.com/api/?${new URLSearchParams(i)}`,r=(await b.get(e)).data;n.classList.remove("visible"),r.hits.length>0?(r.hits.forEach(t=>{const m=document.createElement("li"),a=document.createElement("img"),l=document.createElement("a"),c=document.createElement("div");a.src=t.webformatURL,a.alt=t.tags,l.href=t.largeImageURL,l.appendChild(a),c.classList.add("image-info"),c.innerHTML=`
                    <p class="likes">Likes <span>${t.likes}</span></p>
                    <p class="views">Views <span>${t.views}</span></p>
                    <p class="comments">Comments <span>${t.comments}</span></p>
                    <p class="downloads">Downloads <span>${t.downloads}</span></p>
                `,m.appendChild(l),m.appendChild(c),v.appendChild(m)}),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),S(),p*u>=r.totalHits?(o.classList.remove("visible"),y.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#3498db"})):o.classList.add("visible")):(o.classList.remove("visible"),y.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#3498db"}))}catch(i){console.error("Error fetching more results:",i),n.classList.remove("visible"),o.classList.add("visible")}});function S(){const n=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:n*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
